### PR TITLE
Suppress CocoaPods warning, now it's happy 😄

### PR DESCRIPTION
**Pull request by carlosypunto**
It's not important

### CODE REVIEW

**Comment by carlosypunto** [comment]
I did not want to include the _Podfile.lock_, since you did not include it.

**Comment by icanzilb** [comment]
oh that's great, thanks! it's the CP that sets this flag wrong right? maybe it can be easily fixed in CP itself 🤔

**Comment by carlosypunto** [comment]
When creating a project Xcode puts it in NO, I'm not very sure on what time you switch to YES, but it happens often

**Comment by carlosypunto** [comment]
I've downdate to CocoaPods to 1.1.1, maybe is 1.2.0.beta.1. Do you use it?

**Comment by icanzilb** [comment]
I have 1.1.1 as well, oh well - I'll merge this and we'll figure it out later, thanks again for noticing this

**Comment by carlosypunto** [comment]
Maybe @orta can clarify this doubt

**Comment by carlosypunto** [comment]
@icanzilb The moment when Xcode change this flag is when we accept to "Update to recommend settings" warning 😉

**Pull request merged**
